---
title: "Stablecoins Usage"
description: "An analysis of onchain stablecoins activity"
date: "2025-09-24"
categories: ["analysis", "stablecoins"]
execute:
  enabled: false
  echo: false
format: 
  html:
    code-fold: true
jupyter: python3
image: "images/boss.png"
---

In [1]:
import os, json
from pathlib import Path
import sys
import polars as pl
rootdir = Path.cwd().parent
sys.path.append(str(rootdir))

from onchaindata.utils.database import PostgresClient

client = PostgresClient.from_env()

## Some intresting transactions
Big amounts

In [2]:
query = """
SELECT
    amount,
    token_address,
    from_address,
    to_address,
    transaction_hash
FROM staging.erc20_transfer
WHERE amount > 1e25 -- Adjust threshold
ORDER BY amount DESC
LIMIT 20;
"""
import pandas as pd
df = pd.read_sql(query, client.sqlalchemy_engine)
df

,amount,token_address,from_address,to_address,transaction_hash
0,1.957882e+40,0xbc6da0fe9ad5f3b0d58160288917aa56653660e9,0x303241e2b3b4aed0bb0f8623e7442368fed8faf3,0x0000000000000000000000000000000000000000,0xb23aaecc086996f8059a0de67819b0e45d82e68c2581...
1,1.957882e+40,0xbc6da0fe9ad5f3b0d58160288917aa56653660e9,0x0000000000000000000000000000000000000000,0x303241e2b3b4aed0bb0f8623e7442368fed8faf3,0xb23aaecc086996f8059a0de67819b0e45d82e68c2581...
2,3.214218e+38,0xbc6da0fe9ad5f3b0d58160288917aa56653660e9,0xe1f27add45652812bad02e26eec588f0ef97e1d3,0x0000000000000000000000000000000000000000,0x06712214f077b5bfd9568ca0d32da8633e1ea12bf352...
3,3.214218e+38,0xbc6da0fe9ad5f3b0d58160288917aa56653660e9,0x0000000000000000000000000000000000000000,0xe1f27add45652812bad02e26eec588f0ef97e1d3,0x06712214f077b5bfd9568ca0d32da8633e1ea12bf352...
4,1.012384e+27,0xdc035d45d973e3ec169d2276ddab16f1e407384f,0x691a6c29e9e96dd897718305427ad5d534db16ba,0x0000000000000000000000000000000000000000,0xf5afc2a2299e46c08954b51342257f17bfc02e40bfcd...
5,1.012384e+27,0xdc035d45d973e3ec169d2276ddab16f1e407384f,0x0000000000000000000000000000000000000000,0x629ad4d779f46b8a1491d3f76f7e97cb04d8b1cd,0xdd5bf338720c06dd098216e53a276a8bac00fddd80e9...
6,1.012384e+27,0xdc035d45d973e3ec169d2276ddab16f1e407384f,0xc395d150e71378b47a1b8e9de0c1a83b75a08324,0x691a6c29e9e96dd897718305427ad5d534db16ba,0xf5afc2a2299e46c08954b51342257f17bfc02e40bfcd...
7,1.012384e+27,0xdc035d45d973e3ec169d2276ddab16f1e407384f,0x629ad4d779f46b8a1491d3f76f7e97cb04d8b1cd,0x1601843c5e9bc251a3272907010afa41fa18347e,0xdd5bf338720c06dd098216e53a276a8bac00fddd80e9...
8,1.012384e+27,0xdc035d45d973e3ec169d2276ddab16f1e407384f,0x1601843c5e9bc251a3272907010afa41fa18347e,0xc395d150e71378b47a1b8e9de0c1a83b75a08324,0xf5afc2a2299e46c08954b51342257f17bfc02e40bfcd...
9,4.477562e+26,0x5f98805a4e8be255a32880fdec7f6728c6568ba0,0x903d12bf2c57a29f32365917c706ce0e1a84cce3,0x66017d22b0f8556afdd19fc67041899eb65a21bb,0x167a205d0de566eaf0fa4a7bd1ee850125a4d03c2b0d...
10,4.477562e+26,0x5f98805a4e8be255a32880fdec7f6728c6568ba0,0x0000000000000000000000000000000000000000,0x903d12bf2c57a29f32365917c706ce0e1a84cce3,0x6acdc4e6b6fd224d004c76bb497648550f92e3e8b5f2...
11,4.163991e+26,0xdc035d45d973e3ec169d2276ddab16f1e407384f,0x691a6c29e9e96dd897718305427ad5d534db16ba,0x0000000000000000000000000000000000000000,0xd214a60bbebd28c045e36478adc3f15c65d2d017ffb0...
12,4.163991e+26,0xdc035d45d973e3ec169d2276ddab16f1e407384f,0x1601843c5e9bc251a3272907010afa41fa18347e,0xc395d150e71378b47a1b8e9de0c1a83b75a08324,0xd214a60bbebd28c045e36478adc3f15c65d2d017ffb0...
13,4.163991e+26,0xdc035d45d973e3ec169d2276ddab16f1e407384f,0xc395d150e71378b47a1b8e9de0c1a83b75a08324,0x691a6c29e9e96dd897718305427ad5d534db16ba,0xd214a60bbebd28c045e36478adc3f15c65d2d017ffb0...
14,4.000000e+26,0xdc035d45d973e3ec169d2276ddab16f1e407384f,0xc395d150e71378b47a1b8e9de0c1a83b75a08324,0x3300f198988e4c9c63f75df86de36421f06af8c4,0x4ddc25f122e8092d40a008e2a1807ed81beb514f0543...
15,4.000000e+26,0xdc035d45d973e3ec169d2276ddab16f1e407384f,0x0000000000000000000000000000000000000000,0xc395d150e71378b47a1b8e9de0c1a83b75a08324,0x4ddc25f122e8092d40a008e2a1807ed81beb514f0543...
16,3.031114e+26,0xdc035d45d973e3ec169d2276ddab16f1e407384f,0xc395d150e71378b47a1b8e9de0c1a83b75a08324,0x691a6c29e9e96dd897718305427ad5d534db16ba,0x25cc4ee2f2b5eb885ccf729964794c3257884f21987e...
17,3.031114e+26,0xdc035d45d973e3ec169d2276ddab16f1e407384f,0x691a6c29e9e96dd897718305427ad5d534db16ba,0x0000000000000000000000000000000000000000,0x25cc4ee2f2b5eb885ccf729964794c3257884f21987e...
18,3.031114e+26,0xdc035d45d973e3ec169d2276ddab16f1e407384f,0x0000000000000000000000000000000000000000,0x1601843c5e9bc251a3272907010afa41fa18347e,0x25cc4ee2f2b5eb885ccf729964794c3257884f21987e...
19,3.031114e+26,0xdc035d45d973e3ec169d2276ddab16f1e407384f,0x1601843c5e9bc251a3272907010afa41fa18347e,0xc395d150e71378b47a1b8e9de0c1a83b75a08324,0x25cc4ee2f2b5eb885ccf729964794c3257884f21987e...

## ERC20 transfers count

In [3]:
query = """
SELECT
      token_address,
      COUNT(*) as erc20_transfer_count
  FROM staging.erc20_transfer
  GROUP BY token_address
  ORDER BY erc20_transfer_count DESC
  LIMIT 20;
"""
import pandas as pd
df = pd.read_sql(query, client.sqlalchemy_engine)

with open(rootdir / 'scripts/stablecoins/contracts.json', 'r') as f:
      contracts = json.load(f)

  # Create address to name mapping (convert addresses to lowercase for matching)
address_to_name = {v['address'].lower(): k for k, v in contracts.items()}

# Add token name column to DataFrame
df['stablecoin'] = df['token_address'].str.lower().map(address_to_name)

# Fill NaN values with 'unknown' for tokens not in the mapping
df['stablecoin'] = df['stablecoin'].fillna('unknown')

df[['stablecoin', 'erc20_transfer_count']]

   stablecoin  erc20_transfer_count
0      crvusd               1359555
1        usds                834159
2        lusd                550227
3         gho                475397
4        dola                362099
5        eusd                148279
6       fxusd                 94206
7       alusd                 80357
8        bold                 58566
9        ousd                 57283
10     frxusd                 40915
11       usd3                  8826